Add support for extra su arguments

diff --git a/su b/su
--- a/su
+++ b/su
@@ -1,13 +1,93 @@
 #!/QOpenSys/usr/bin/sh
-#
-# NOTE: if you want to 'su' without a password, run su-setup first
-#
-if [ "$1" == "" ] ; then
+usage() {
 	echo "Usage:" $(basename $0) "<username>"
 	exit 5
+}
+
+if [ "$1" == "" ] ; then
+	usage
 fi
 SSH_OPTS="-Y"
 if [ "$DISPLAY" == "" ] ; then
 	SSH_OPTS="-x"
 fi
-exec /QOpenSys/usr/bin/ssh $SSH_OPTS $1@127.0.0.1
+
+#Input 
+RMT_USER=$1
+RMT_DIR=$(pwd)
+RMT_SHELL='$SHELL'
+RMT_CMD=""
+RMT_SHELL_ENVARGS=""
+
+
+shift
+while [ "$1" != "" ]; do
+    PARAM=`echo $1 | awk -F= '{print $1}'`
+    VALUE=`echo $1 | awk -F= '{print $2}'`
+    case $PARAM in
+        -h | --help)
+            usage
+            ;;
+        --command|--session-command)
+            RMT_CMD=$VALUE
+            ;;
+        -c) 
+        	shift
+        	RMT_CMD=$1
+        	if [ "$1" == "" ]; then
+        		usage
+        	fi
+        	;;
+        --shell)
+            RMT_SHELL=$VALUE
+            ;;
+        --fast|-f)
+            RMT_SHELL_OPTS="$RMT_SHELL_OPTS -f"
+            ;;
+        -s) 
+        	shift
+        	RMT_SHELL=$1
+        	if [ "$1" == "" ]; then
+        		usage
+        	fi
+        	;;
+        -m|-p|--preserve-environment)
+        	RMT_SHELL_ENVARGS=$(env | grep -Ev '^(USER|HOME|LOGNAME|SHELL)' | awk '{printf "export \"%s\" && ",$1; }')
+        	;;
+        --group|-g|-G|--supp-group)
+        	>&2 echo "ERROR: Option $PARAM not supported"
+        	exit 7
+        	;;
+   		-|-l|--login) 
+        	>&2 echo "WARNING: Option $PARAM not fully supported (always a login shell; this option causes a change to the target user's home directory)"
+        	RMT_DIR=""
+        	;;
+      	--version|-V)
+      		echo "Jesse's Poor-Man su, version 1"
+      		exit 2
+      		;;
+        *)
+            echo "ERROR: unknown parameter \"$PARAM\""
+            usage
+            exit 1
+            ;;
+    esac
+    shift
+done
+
+
+
+if [ "$RMT_CMD" == "" ] ; then
+	if [ "$RMT_SHELL_ENVARGS" == "" ] ; then
+		RMT_CMD="cd $RMT_DIR && exec $RMT_SHELL -l "
+	else
+		RMT_CMD="cd $RMT_DIR && exec $RMT_SHELL -l -c '$RMT_SHELL_ENVARGS exec $RMT_SHELL' "
+	fi
+else
+	RMT_CMD="cd $RMT_DIR && exec $RMT_SHELL -l -c '$RMT_SHELL_ENVARGS $RMT_CMD' "
+fi
+
+
+
+#echo $RMT_CMD
+exec /QOpenSys/usr/bin/ssh -q -t $SSH_OPTS $RMT_USER@127.0.0.1  $RMT_CMD
